[feature] - add enable cache buster
module-federation/federation-dashboard pull request #467
Opened 2023-09-12 06:52 UTC by nattaaek

2023-09-12 13:06 UTC, edusperoni requested changes
Hello! Thanks for this. I've added some comments to keep the code consistent

2023-09-12 13:06 UTC, edusperoni commented on dashboard-plugin/client-version.js
> +  enableCacheBuster = enableCacheBuster || false
re-add semicolons. switch to fallbackEnableCacheBuser so it's clear the cachebuster is for fallback only

2023-09-12 13:06 UTC, edusperoni commented on dashboard-plugin/client-version.js
> +      dashboardTimeout = -1
remove extra white space indentation, add semicolon

2023-09-12 13:06 UTC, edusperoni commented on dashboard-plugin/client-version.js
> +      throw new Error('Invalid dashboardTimeout')
remove extra white space indentation, add semicolon

2023-09-12 13:06 UTC, edusperoni commented on dashboard-plugin/client-version.js
> +  // language=JS
remove whitespace difference

2023-09-12 13:06 UTC, edusperoni commented on dashboard-plugin/client-version.js
> +          }
remove extra (2) whitespaces to make it consistent with the rest of the code in this section

2023-09-12 13:06 UTC, edusperoni commented on dashboard-plugin/client-version.js
> +}
add semicolons

2023-09-12 13:52 UTC, edusperoni approved these changes

2023-09-13 11:57 UTC, valorkin approved these changes

2023-09-13 12:01 UTC, merged